import React from 'react';

export const PostPreview10 = () => (
    <article id="post-698" className="post-698 post type-post status-publish format-standard has-post-thumbnail hentry category-market category-technology category-thoughts-on-the-future">
        <div className="entry-featured">
            <div className="entry-thumb"><img width="700" height="300" src="http://abraxastechnology.com/wp-content/uploads/2018/04/enterprise-data-science.png" className="attachment-entry-fullwidth size-entry-fullwidth wp-post-image" alt=""/></div>  </div>
        <div className="entry-wrap">

            <header className="entry-header">
                <h1 className="entry-title">The Most Successful Companies Today Are Data-Driven</h1>
                <p className="p-meta"><span><i className="x-icon-pencil" data-x-icon=""></i> Aaron Tao</span><span><time className="entry-date" dateTime="2018-04-09T13:47:25+00:00"><i className="x-icon-calendar" data-x-icon=""></i> April 9, 2018</time></span><span><a href="http://abraxastechnology.com/blog/market" title="View all posts in: “Market”"><i className="x-icon-bookmark" data-x-icon=""></i> Market</a>, <a href="http://abraxastechnology.com/blog/technology" title="View all posts in: “Technology”"><i className="x-icon-bookmark" data-x-icon=""></i> Technology</a>, <a href="http://abraxastechnology.com/blog/thoughts-on-the-future" title="View all posts in: “Thoughts on the Future”"><i className="x-icon-bookmark" data-x-icon=""></i> Thoughts on the Future</a></span><span><a href="http://abraxastechnology.com/the-most-successful-companies-today-are-data-driven#respond" title="Leave a comment on: “The Most Successful Companies Today Are Data-Driven”" className="meta-comments"><i className="x-icon-comments" data-x-icon=""></i> Leave a Comment</a></span></p></header>


            <div className="entry-content content">


                <p>As a data nerd and product marketer, I never cease to be amazed by what data science can reveal about people’s preferences, moods, and behavior. These applications can range from the amusing to potentially life-saving. From its analysis of online interactions between couples, <a href="https://www.facebook.com/data/">Facebook Data Science</a> can predict with astounding accuracy the likelihood of <a href="https://www.facebook.com/notes/facebook-data-science/the-formation-of-love/10152064609253859">budding relationships</a> and <a href="https://www.facebook.com/notes/facebook-data-science/when-love-goes-awry/10152066701893859/?fref=mentions">break ups</a>. <a href="https://www.sciencedaily.com/releases/2017/05/170509121952.htm">Using Twitter data</a>, researchers at Northeastern University developed a model to accurately predict flu outbreaks up to six weeks in advance.</p>
                <p>Data analytics is being used by more and more companies to allow them to make better decisions, develop new products and services, and verify or refute existing theories or models. <a href="https://www.mckinsey.com/business-functions/mckinsey-analytics/our-insights/capturing-value-from-your-customer-data">According to McKinsey research</a>, “organizations that leverage customer behavioral insights outperform peers by 85 percent in sales growth and more than 25 percent in gross margin.” Perhaps then it is no surprise that some of the most innovative products, services, processes, and solutions were developed by companies that successfully leveraged and applied the customer insights that came from big data.</p>
                <p>The names of companies who have outperformed their peers through data are now household names. Amazon, Google and Netflix have all successfully used data to understand, market to, and increase revenue from their customers. Guided by its mission statement to become “<a href="http://delight.us/earths-most-customer-centric-company/">Earth’s Most Customer-Centric Company</a>,” Amazon is currently one of today’s <a href="http://fortune.com/worlds-most-admired-companies/amazon-com/">most admired companies</a> (in addition to enjoying an impressive <a href="https://ycharts.com/companies/AMZN/free_cash_flow">$7.4 billion free cash flow as of December 2017</a>). Google, now known as Alphabet, makes <a href="https://www.investopedia.com/articles/investing/020515/business-google.asp">90% of its $89.5 billion revenue from Google Adwords</a>.&nbsp;<a href="https://blog.kissmetrics.com/how-netflix-uses-analytics/">Drawing on data analytics that combed through subscribers’ viewing habits and gathered valuable insights</a>, Netflix produced heavily personalized content and became the biggest streaming service in the United States.</p>
                <p>Amazon, Google, and Netflix may all have different business models but all three of these tech titans built their vast empires with a core focus on customer behavior data and analytics. Clayton Christensen, author of the best-selling classNameic <a href="https://www.amazon.com/Innovators-Dilemma-Technologies-Management-Innovation/dp/1633691780/"><em>The Innovator’s Dilemma</em></a>, has taken pains to point out that customers aren’t really interested in products or services themselves but in what they do, specifically “<a href="https://hbr.org/2016/09/know-your-customers-jobs-to-be-done">jobs to be done</a>.” Christensen further elaborates:</p>
                <blockquote><p>Identifying and understanding the job to be done are only the first steps in creating products that customers want—especially ones they will pay premium prices for. It’s also essential to create the right set of experiences for the purchase and use of the product and then integrate those experiences into a company’s processes.</p></blockquote>
                <p>Successful companies such as Amazon, Google, and Netflix know that they have to go beyond knowing “who” their customers are. Specifically, they rely on data analytics as revealed through their customers’ behaviors to obtain a more accurate picture of what they really want and need, and how and when to best deliver it to them.</p>
                <p>For the out-of-home (OOH) advertising industry, the landscape has remained virtually unchanged since the 1990s. While OOH advertising still possesses many advantages and is <a href="http://abraxastechnology.com/you-wont-believe-why-which-advertising-medium-is-forecasted-to-grow-the-fastest">positioned to grow</a>, OOH mediums cannot record or provide any meaningful consumer data to advertisers. These shortcomings severely limit an OOH owner’s ability to gain new customers and increase ad spends. In today’s economy, companies are constantly reinventing themselves through customer-centricity, personalization, and customer experience. Data-driven analytics and quantitative insights are the must-have tools.</p>
                <p>The key takeaway for OOH owners is that in order for them to increase their revenue and amount of ad spend within a marketing campaign, they cannot just rely on the number of weekly impressions. They also have to provide qualitative data that allows for marketers to gain a deeper understanding of consumers’ motivations, context, and triggers. Having grown used to the data that online marketing platforms provide, marketers and advertisers are now demanding the same from the OOH market (traits that we at <a href="http://abraxastechnology.com/">Abraxas Technology</a> have built into our product).</p>
                <p>From the surveys and interviews that we have conducted at Abraxas Technology, the number one qualitative attribute that marketers and advertisers need before increasing their ad spends with OOH owners is knowing which billboards are producing results for their campaigns. This requires data showing customer conversions from the billboards to the store.</p>
                <p>Industries unable or too slow to apply customer-centric, behavioral data-driven strategies in their business models will be at greater risk of <a href="http://abraxastechnology.com/dont-get-blown-away-by-the-gale-of-creative-destruction">obsolescence</a>. Owners and advertisers who have access to customer data and understand their behavior can then effectively make use of their ad spend and position themselves for future market expansion. Ultimately, OOH owners have to join the 21<sup>st</sup> century in order to remain successful companies.</p>
                <p>______________________________________________________________________________</p>
                <p><a href="https://www.linkedin.com/in/aarontao/"><strong>Aaron Tao</strong></a> is a Product Manager with Abraxas Technology.</p>
                <p>Reach out to us today if you want to begin providing relevant data to marketers and advertisers. Email <a href="mailto:JLawton@abraxastechnology.com">JLawton@abraxastechnology.com</a>.</p>
                <p><em>Follow us on Twitter </em><a href="https://twitter.com/Abraxas_Tech"><em>@</em></a><a href="https://twitter.com/Abraxas_Tech"><strong><em>Abraxas_Tech</em></strong></a></p>


            </div>

        </div>

    </article>
);

export default PostPreview10;
