import React from 'react';

export const PostPreview13 = () => (
    <article id="post-628" className="post-628 post type-post status-publish format-standard has-post-thumbnail hentry category-market category-technology category-thoughts-on-the-future tag-creative-destruction tag-data-analytics tag-innovation tag-software tag-toys-r-us">
        <div className="entry-featured">
            <div className="entry-thumb"><img width="600" height="400" src="http://abraxastechnology.com/wp-content/uploads/2018/03/ToysRUsClosingDownSale.jpg" className="attachment-entry-fullwidth size-entry-fullwidth wp-post-image" alt=""/></div>  </div>
        <div className="entry-wrap">

            <header className="entry-header">
                <h1 className="entry-title">Don’t Get Blown Away by the Gale of Creative Destruction</h1>
                <p className="p-meta"><span><i className="x-icon-pencil" data-x-icon=""></i> Aaron Tao</span><span><time className="entry-date" dateTime="2018-03-22T17:50:13+00:00"><i className="x-icon-calendar" data-x-icon=""></i> March 22, 2018</time></span><span><a href="http://abraxastechnology.com/blog/market" title="View all posts in: “Market”"><i className="x-icon-bookmark" data-x-icon=""></i> Market</a>, <a href="http://abraxastechnology.com/blog/technology" title="View all posts in: “Technology”"><i className="x-icon-bookmark" data-x-icon=""></i> Technology</a>, <a href="http://abraxastechnology.com/blog/thoughts-on-the-future" title="View all posts in: “Thoughts on the Future”"><i className="x-icon-bookmark" data-x-icon=""></i> Thoughts on the Future</a></span><span><a href="http://abraxastechnology.com/dont-get-blown-away-by-the-gale-of-creative-destruction#respond" title="Leave a comment on: “Don’t Get Blown Away by the Gale of Creative Destruction”" className="meta-comments"><i className="x-icon-comments" data-x-icon=""></i> Leave a Comment</a></span></p></header>


            <div className="entry-content content">


                <p>For Millennials, many of their cherished childhood memories involve exploring their local Toys R Us, getting awestruck by the endless aisles of toys in all shapes and colors, and walking home with the latest NERF gun or LEGO kit. This month, the <a href="http://www.businessinsider.com/why-toys-r-us-is-closing-stores-2018-3">announcement</a> that Toys R Us is finally closing all its stores and liquidating all its assets made major headlines. Looking back with <a href="http://www.businessinsider.com/toys-r-us-closing-stores-fond-memories-photos-2018-3">nostalgia</a>, I can’t help but feel a twinge of sadness but as an entrepreneur, I understand that <a href="https://hbr.org/2015/12/what-is-disruptive-innovation">disruptive innovation</a> is an inevitable reality in the increasingly competitive 21<sup>st</sup> century economy.</p>
                <p>Established titans such as Blockbuster Video, Borders Books, Kodak, and Sears have been completely swept away by the gales of “<a href="http://www.learnliberty.org/blog/youre-in-joseph-schumpeters-economy-now/">destructive creation</a>,” in the words of economist Joseph Schumpeter, or have been reduced to shells of their former selves. Brick and mortar retail, in particular, <a href="https://www.washingtonpost.com/news/innovations/wp/2017/05/15/the-gradual-then-sudden-disruption-of-retail/?utm_term=.2581936c833b">has been hit hard</a> with the advent of ecommerce, and it is not surprising that market leader <a href="http://abcnews.go.com/amp/Business/wireStory/toys-us-joins-bankruptcy-list-amazon-exerts-influence-49965021">Amazon has claimed another scalp</a> with the fall of Toys R Us.</p>
                <p>These on-going trends are consistent with the observations highlighted in Marc Andreessen’s famous 2011 article “<a href="https://www.wsj.com/articles/SB10001424053111903480904576512250915629460">Why Software Is Eating The World</a>.”</p>
                <blockquote><p>We are in the middle of a dramatic and broad technological and economic shift in which software companies are poised to take over large swathes of the economy. More and more major businesses and industries are being run on software and delivered as online services — from movies to agriculture to national defense.</p></blockquote>
                <p>The continuing success of Amazon, Netflix, and other tech startups indicate that the software revolution is not over. As more and more companies integrate software into their business models, it is not surprising that data-driven approaches have dramatically transformed traditional marketing strategy. In the case of Netflix, its original hit show <a href="https://www.netflix.com/title/70178217"><em>House of Cards</em></a> was produced and launched through <a href="http://www.nytimes.com/2013/02/25/business/media/for-house-of-cards-using-big-data-to-guarantee-its-popularity.html">collection and analysis of its subscribers’ streaming habits</a>.</p>
                <p>Despite all the apps and information available, a November 2017 Google white paper, “<a href="https://services.google.com/fh/files/misc/google-data-driven-marketers-strategic-playbook.pdf">The Data-Driven Marketer’s Strategic Playbook</a>, reveals that “61% of marketing decision makers said they still struggled to access or integrate the data they had needed that year.” While nearly 2/3rds of executives in leading companies say that they value data-driven insights over gut intuition, many decision makers “still struggle with data blindness, not knowing what data they have or how it fits together.”</p>
                <p>This is a special challenge for out-of-home (OOH) advertising companies. By themselves, billboards (both traditional and digital), bench signs, and other OOH mediums cannot record or provide any meaningful consumer data to advertisers. This significantly impacts an OOH owner’s ability to gain new clients and increase ad spends. Nevertheless, billboards and signage are still very <a href="http://abraxastechnology.com/understanding-technology-options-for-ooh-owners-and-advertisers">effective when it comes to visibility, reach, and impressions</a>.</p>
                <p>Bridging the best of both worlds by integrating capabilities only seen in the online advertising space with the unique characteristics of the Out of Home industry is necessary for the latter’s continued growth (this is exactly why OOH owners are clients of <a href="http://abraxastechnology.com/">Abraxas Technology</a>). Marketers who know their data from origins to application are best positioned for future success. They should also be willing to not only continue with an existing advertising medium, but also be open to experimenting with new channels and methods. OOH owners and managers who have invested in the proper resources, tools, and personnel necessary to understand and react to sweeping changes in consumer and advertiser behavior and demands will position themselves for market penetration and growth.</p>
                <p>For the OOH industry, that means embracing the promise and potential of data analytics. Luckily, there are many <a href="http://abraxastechnology.com/understanding-technology-options-for-ooh-owners-and-advertisers">technology options out there for OOH owners and advertisers</a>, as highlighted by my colleague Joshua Lawton. While each company’s needs and end goals can widely differ, OOH advertisers must find some way of collecting meaningful data and respond appropriately to changing market conditions. One ignores this landscape at his or her own peril. In the words of <a href="https://twitter.com/geoffreyamoore">Geoffrey Moore</a>, “Without ‘big data’, you are blind and deaf and in the middle of a freeway.” For a company to remain competitive in the 21<sup>st</sup> century, that means adopting the best practices and processes.</p>
                <p>As summarized in Google’s <a href="https://services.google.com/fh/files/misc/google-data-driven-marketers-strategic-playbook.pdf">white paper</a>:</p>
                <blockquote><p>Marketing organizations paving the way have recognized that there are three things that go better together in today’s world: data, that is well-integrated to provide a more complete view of each customer; teams, that increase collaboration, communication, and sharing of data and audience insights; and technology, that unifies analytics and advertising stacks so marketers can deliver more relevant, engaging customer experiences and value to the business.</p></blockquote>
                <p>But perhaps most importantly, the best business leaders devote themselves to building organizations with an ingrained culture for continual innovation. With <a href="https://www.research.ibm.com/5-in-5/">artificial intelligence and blockchain</a> likely to become key drivers for the foreseeable future, the impact of emerging technologies on business models will only intensify.</p>
                <p>Organizations can’t afford to remain in one fixed state or they will quickly be rendered obsolete and join Blockbuster, Toys R Us, and other dinosaurs in the dust bin of history.</p>
                <p>______________________________________________________________________________</p>
                <p><strong><a href="https://www.linkedin.com/in/aarontao/">Aaron Tao</a></strong> is a Product Manager with Abraxas Technology.</p>
                <p>Reach out to us today if you want to begin providing relevant data to marketers and advertisers. Email <a href="mailto:JLawton@abraxastechnology.com">JLawton@abraxastechnology.com</a>.</p>
                <p><em>Follow us on Twitter </em><a href="https://twitter.com/Abraxas_Tech"><em>@</em></a><a href="https://twitter.com/Abraxas_Tech"><strong><em>Abraxas_Tech</em></strong></a></p>


            </div>

        </div>

        <footer className="entry-footer cf">
            <a href="http://abraxastechnology.com/tag/creative-destruction" rel="tag">creative destruction</a><a href="http://abraxastechnology.com/tag/data-analytics" rel="tag">data analytics</a><a href="http://abraxastechnology.com/tag/innovation" rel="tag">innovation</a><a href="http://abraxastechnology.com/tag/software" rel="tag">software</a><a href="http://abraxastechnology.com/tag/toys-r-us" rel="tag">Toys R Us</a>  </footer>
    </article>
);

export default PostPreview13;
