import React from 'react';

export const PostPreview16 = () => (
    <article id="post-619" className="post-619 post type-post status-publish format-standard has-post-thumbnail hentry category-technology tag-advertising tag-billboards tag-marketing tag-ooh tag-technology">
        <div className="entry-featured">
            <div className="entry-thumb"><img width="874" height="472" src="http://abraxastechnology.com/wp-content/uploads/2018/03/Screen-Shot-2018-03-22-at-9.45.23-AM.png" className="attachment-entry-fullwidth size-entry-fullwidth wp-post-image" alt=""/></div>  </div>
        <div className="entry-wrap">

            <header className="entry-header">
                <h1 className="entry-title">Understanding Technology Options for OOH Owners and Advertisers</h1>
                <p className="p-meta"><span><i className="x-icon-pencil" data-x-icon=""></i> Joshua Lawton</span><span><time className="entry-date" dateTime="2018-03-22T14:47:50+00:00"><i className="x-icon-calendar" data-x-icon=""></i> March 22, 2018</time></span><span><a href="http://abraxastechnology.com/blog/technology" title="View all posts in: “Technology”"><i className="x-icon-bookmark" data-x-icon=""></i> Technology</a></span><span><a href="http://abraxastechnology.com/understanding-technology-options-for-ooh-owners-and-advertisers#respond" title="Leave a comment on: “Understanding Technology Options for OOH Owners and Advertisers”" className="meta-comments"><i className="x-icon-comments" data-x-icon=""></i> Leave a Comment</a></span></p></header>


            <div className="entry-content content">


                <p>OOH owners and advertisers are being swamped by technological advancements, all of which are promising insight that until this time has not been available in the Out of Home market. As a member of OAAA’s Innovations Committee and as the COO and Co-Founder of <a href="http://abraxastechnology.com/">Abraxas Technology</a>, I am often asked by those in the OOH industry about which technology is best for them to use to increase sales and show a return on investment for advertisers. You might find this hard to believe, but I do not always recommend our own technology. I know that we are the best at what we do (being able to passively collect data to show conversions, IE if somebody saw a billboard and then appeared in the store or online), however depending on the use case there are other options available.</p>
                <p>That said, it can be difficult for OOH owners and advertisers to not only understand the different options, but also have the data to back why or why not they should use one technology over another. To that end, below is an explanation of the different technologies available and what they can optimally do and what they cannot optimally do.</p>
                <p><strong>Camera technology:</strong> Camera technology is a system to count the number of impressions. While some camera technology companies only claim to be able to count the number of impressions, others claim to be able to provide you with the ability to know if an impression actually interacted/looked at your advertisement and how they felt. While the ability to track eye movement with heat maps is well established, there are some great studies on the problems that are inherent in tracking human emotions. I do not want to inundate you with tons of studies, so I’ll link you to one of the major reputable studies done by the National Institutes of Health. In short, the summary of the report is:&nbsp;<em>“</em><em>Despite recent progress, studies on human emotions have been hindered by the lack of consensus on an emotion theory suited to examining the dynamic aspects of emotion and its expression.”</em><em>&nbsp;</em> Secondly, pure counts of impressions are not the main focus for OOH advertisers. Conversions and durations of impressions are the primary ways by which OOH owners can increase their revenues because that is what is being demanded by advertisers. The ability to know whether or not someone saw an OOH ad and that went into the store is at odds with the current capabilities of the best facial recognition systems that are based on neural/deep networks. According a recent academic study,&nbsp;<em>”&nbsp;</em><em>When people are wearing a hat, scarf, and glasses to cover their faces… algorithms were able to identify people with around 55 percent accuracy. The figure rose to 69 percent when just glasses were removed.”</em>&nbsp;(Therefore, tracking in store conversions from out of store becomes difficult, and the ability to track frequency of impressions, conversions, etc. becomes hugely problematic for highly advanced biometric systems, of which I am highly skeptical is available to OOH advertisers at this time.</p>
                <p>That said, if the intent is to only collect the number of impressions for a piece of OOH media, camera technology should work for you.</p>
                <p><strong>iBeacon</strong>: iBeacon is a solution that was released by Apple. It has an interesting framework, and Apple’s vertical siloed integration amongst its own products is well known and is beneficial to developers. However, this product only works on iBeacon enabled hardware and iOS apps. Furthermore, it requires a user to download an app that has iBeacon integrated into it. Therefore, it has a serious friction point that hinders efficacy, because users have to actively download an app. Efficacy is also hindered because the standard beacon technology has a range of 70 meters. Added to range issues, only 46% of Americans in 2016 owned an iPhone. Therefore, in order for this technology to be of use, an advertiser must be able to have consumers, that own iPhones, who responds to calls of action to download an app.</p>
                <p>Not to be confused with all beacon technologies, iBeacon is highly specific and should really only be considered if you know if a majority of your customers have an iPhone. However, if you do have a highly engaged community that has downloaded your app in the past, iBeacon could be an appropriate technology to use.</p>
                <p><strong>Bluetooth collection products</strong>: Beyond the fact that close to 60% of Americans turn off their Bluetooth connections on a regular basis, there are other serious issues with integrating a Bluetooth collection product. The Physical Web beacon protocol that is used in browsers are very basic tools and are currently not supported on Android devices. Secondly, if relying on this protocol, it requires users not to prevent cookies and hashes on their devices or delete or prevent cookies and preferences on their devices. The two main other protocols are iBeacon (as mentioned above) and Eddystone. Currently there is no industry standard and the way that Eddystone works is different on an Android device versus how it works on an Apple device.&nbsp;Range is also a limiting factor with these devices because the standard range for Bluetooth collection products (think beacons) is 70 meters.</p>
                <p>If you have development resources or can use a team that is used to working with Eddystone this can be a possible path forward. There are companies that do the integration of these protocols into websites and for some OOH media this can be an appropriate technology. However, for those who want to use technology to track impressions on Billboards, I would suggest not using this technology.</p>
                <p><strong>App based location:</strong> This requires the device’s location services to be turned on and the app’s location services to be turned on. Furthermore, a user has to download the app and updating the app can present problems if updates are not done in time or the app’s architecture changes.</p>
                <p>I am highly dubious of purely relying on app based location for the OOH market. There are way too many variables and confidence intervals are huge.</p>
                <p><strong>Passive electronic signature collection</strong>: Passive electronic signature collection comes in many forms. Some technologies use what is known as a man-in-the-middle solution that creates a fake connection point that a cell phone tries to connect to and is immediately denied connection. While not illegal in the United States, this technique presents issues under GDPR. These technologies passively listen for electronic signatures to show the number of impressions. However, because they cannot accurately get to the device’s real address, they are not able to track conversions. <a href="http://abraxastechnology.com/">Abraxas</a> is different than these types of offerors on the market that passively listen for electronic signatures because we are able to obtain the device’s real address and show conversions in-store and online. The benefit of any passive electronic signature technology is that a user does not need to opt in to or download anything.</p>
                <p>If tracking conversions into an advertiser’s store or stores is the added value that an OOH owner or media buyer wants to provide, this is a technology that you want to use. Due to the fact that the conversion capability also results in the ability to show the frequency of an impression, OOH owners and media buyers who use this technology have key insights into pricing OOH media. Because Apple and Android both change how they obfuscate devices from time to time, it is important to work with a company that you trust will be able to keep up when Apple and Android put out new protocols to obfuscate their devices.</p>
                <p>&nbsp;</p>
                <p>Reach out to us today if you want to begin providing relevant data to marketers and advertisers. Email&nbsp;<a href="mailto:JLawton@abraxastechnology.com">JLawton@abraxastechnology.com</a>.</p>
                <p>Joshua Lawton is the COO and Co-Founder of Abraxas Technology.</p>
                <p><strong><i>Follow us on Twitter&nbsp;</i><a href="https://twitter.com/Abraxas_Tech"><i>@</i><i>Abraxas_Tech</i></a>.</strong></p>
                <p>&nbsp;</p>
                <p>&nbsp;</p>
                <p>Sources Used:</p>
                <p><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4734883/">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4734883/</a></p>
                <p><a href="https://arxiv.org/abs/1708.09317">https://arxiv.org/abs/1708.09317</a></p>
                <p><a href="https://www.macrumors.com/2017/04/20/iphone-ownership-all-time-high-us/">https://www.macrumors.com/2017/04/20/iphone-ownership-all-time-high-us/</a></p>
                <p><a href="https://support.kontakt.io/hc/en-gb/articles/201349702-What-is-the-range-of-each-beacon-">https://support.kontakt.io/hc/en-gb/articles/201349702-What-is-the-range-of-each-beacon-</a></p>


            </div>

        </div>

        <footer className="entry-footer cf">
            <a href="http://abraxastechnology.com/tag/advertising" rel="tag">advertising</a><a href="http://abraxastechnology.com/tag/billboards" rel="tag">billboards</a><a href="http://abraxastechnology.com/tag/marketing" rel="tag">marketing</a><a href="http://abraxastechnology.com/tag/ooh" rel="tag">OOH</a><a href="http://abraxastechnology.com/tag/technology" rel="tag">technology</a>  </footer>
    </article>
);

export default PostPreview16;
