import React from 'react';

export const PostPreview11 = () => (
    <article id="post-670" className="post-670 post type-post status-publish format-standard has-post-thumbnail hentry category-food category-market category-restaurants">
        <div className="entry-featured">
            <div className="entry-thumb"><img width="1039" height="719" src="http://abraxastechnology.com/wp-content/uploads/2018/03/MeatTornado.jpg" className="attachment-entry-fullwidth size-entry-fullwidth wp-post-image" alt=""/></div>  </div>
        <div className="entry-wrap">

            <header className="entry-header">
                <h1 className="entry-title">Marketing the Message and Majesty of Meat</h1>
                <p className="p-meta"><span><i className="x-icon-pencil" data-x-icon=""></i> Aaron Tao</span><span><time className="entry-date" dateTime="2018-03-29T20:34:48+00:00"><i className="x-icon-calendar" data-x-icon=""></i> March 29, 2018</time></span><span><a href="http://abraxastechnology.com/blog/food" title="View all posts in: “Food”"><i className="x-icon-bookmark" data-x-icon=""></i> Food</a>, <a href="http://abraxastechnology.com/blog/market" title="View all posts in: “Market”"><i className="x-icon-bookmark" data-x-icon=""></i> Market</a>, <a href="http://abraxastechnology.com/blog/restaurants" title="View all posts in: “Restaurants”"><i className="x-icon-bookmark" data-x-icon=""></i> Restaurants</a></span><span><a href="http://abraxastechnology.com/marketing-the-message-and-majesty-of-meat#respond" title="Leave a comment on: “Marketing the Message and Majesty of Meat”" className="meta-comments"><i className="x-icon-comments" data-x-icon=""></i> Leave a Comment</a></span></p></header>


            <div className="entry-content content">


                <p>As a Texan and foodie, I am always on the lookout for new BBQ joints and exotic culinary experiences. Thus, learning about the existence of <a href="https://estancia.com/">Estância Brazilian Steakhouse</a> here in Austin aroused my inner carnivore just like when the <a href="https://www.youtube.com/watch?v=bI74fQE--Rs">very mention of “meat tornado” excited Ron Swanson</a>.</p>
                <p>As a regular driver up US-183, I can’t help but look at billboards and lo and behold, I spotted one promising an “authentic” Brazilian steakhouse experience right here in town. Even though I couldn’t go to the restaurant right way, the message of meat stuck in my head. A few weeks later, I spotted another out-of-home (OOH) advertisement, this time on a bus, that tempted me with all-you-can-eat meat prepared with the flavor and culture of Brazil. Still, the busy life of an entrepreneur told my stomach to put its desires on hold. But my dreams became reality within a very short time.</p>
                <p>A few days ago, my colleague Joshua Lawton invited me to join him at this very steakhouse for a team celebration dinner: a toast to our <a href="https://www.quakecapital.com/blog/abraxas-technology">recent success</a>. Walking up the steps of Estância Brazilian Steakhouse, I trembled with excitement.</p>
                <p><img className="wp-image-655 size-large alignnone" src="http://abraxastechnology.com/wp-content/uploads/2018/03/EstânciaBrazilianSteakhouse-1024x768.jpg" alt="" width="1024" height="768"/></p>
                <p><img className=" wp-image-654 alignright" src="http://abraxastechnology.com/wp-content/uploads/2018/03/REcjjOY.gif" alt="" width="496" height="320"/>Needless to say, the evening was a gastronomic delight. Waiters brought out <a href="https://estancia.com/menu/meats/">meat after meat</a> until I could eat no more. House special sirloin, slow-roasted sausage, pork tenderloin, leg of lamb, beef ribs, I had them all. Ron Swanson would have been in heaven.</p>
                <p>Speaking as a marketer, I have to commend Estância’s successful OOH advertising campaign in Austin. Their cleverly-placed and attractive ads definitely played a role in piquing my interest, and reflecting on my excellent dining experience, I have no doubt that I will return in the future.</p>
                <p>The effectiveness of OOH advertising for the restaurant industry cannot be overstated, as previously <a href="http://abraxastechnology.com/6-points-to-get-ooh-in-the-restaurant-marketing-budget">highlighted</a> by my colleague Joshua (with a few updated bullets of my own):</p>
                <ul>
                    <li><a href="http://www.lamar.com/howtoadvertise/~/media/7845006D467B432592A4A1867BBFBA7D.ashx">40% of adults</a> who viewed OOH media in the past month visited the restaurant that was advertised.</li>
                    <li>Directional billboard advertisements have a serious impact on sales. In one <a href="http://www.fliphound.com/files/billboard-out-of-home-advertising-resources/wendys-restaurant-new-location-billboard-campaign-oaaa-case-study.pdf">study</a>, a Wendy’s directional billboard advertisements increased sales by 32% within the first week of being posted.</li>
                    <li><a href="https://www.forbes.com/sites/alexandratalty/2016/10/17/millennials-spend-44-percent-of-food-dollars-on-eating-out-says-food-institute/#36f4406c3ff6">According</a> to the Food Institute’s analysis of the U.S. Department of Agriculture’s <a href="https://www.ers.usda.gov/data-products/food-expenditures.aspx">food expenditure data</a> from 2014, Millennials spent 44% of their annual food dollars eating out. Baby Boomers spent 40% of their annual food dollars eating out.</li>
                    <li>In spite of rising restaurant prices, <a href="https://usa.visa.com/dam/VCOM/global/partner-with-us/documents/consumer-grocery-spending-highlights.pdf">people prefer dining out than cooking at home</a>. One analyst in the <i>Harvard Business Review</i> goes so far as to <a href="https://hbr.org/2017/09/the-grocery-industry-confronts-a-new-problem-only-10-of-americans-love-cooking">predict</a> that grocery shopping and cooking will become a “niche activity that a few people do only some of the time.</li>
                </ul>
                <p>With the rise of the <a href="https://www.washingtonpost.com/lifestyle/food/for-millennials-food-isnt-just-food-its-community/2013/10/22/b6068902-35f2-11e3-8a0e-4e2cf80831fc_story.html?utm_term=.ebf95e463d8c">foodie culture and community</a>, perhaps it is not surprising that the most exciting innovations in the food and restaurant industries are taking place at the grassroots level. Throughout the country, <a href="https://www.economist.com/blogs/graphicdetail/2017/05/daily-chart-3">food truck businesses are rapidly expanding</a>. And in the (literal) <a href="https://www.amazon.com/Made-America-Heritage-Cookbook-Contributions/dp/1615828893">melting pot</a> that showcases the best of Americana, new ethnic food establishments such as <a href="http://kemuri-tatsuya.com/">Kemuri Tatsu-Ya</a> here in Austin are finding a welcome reception by <a href="https://austin.eater.com/2017/7/6/15928340/kemuri-tatsu-ya-texas-ramen-brisket-video">blending Japanese flavors with traditional Texan ingredients such as BBQ brisket</a>.</p>
                <p>Texas is already <a href="https://www.texasmonthly.com/food/texas-food-conquers-the-world/">world-renowned</a> for its cuisine and that distinction is <a href="https://www.texasmonthly.com/food/the-food-issue/">central to our identity</a>. It goes without saying that “<a href="https://www.texasmonthly.com/food/the-list-the-top-50-barbecue-joints-in-texas/">Texas BBQ has no peer on earth</a>.” Salt Lick BBQ is one of central Texas’s most famous BBQ joints. I know of several billboards scattered on freeways that tell drivers which exit to take to reach Salt Lick. People travel here from all over the country to taste some of the best BBQ in the land. For those visitors, a strategically-placed billboard will drive the message home and guide them to their destination.</p>
                <p>Given its <a href="http://www.reaganoutdoor.com/storage/app/media/ArbitronOutOfHomeAdvertisingStudy.pdf#%5B%7B%22num%22%3A6%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C75%2C720%2C0%5D">well-documented advantages</a>, I have no doubt OOH advertising will continue to play an important role in how restaurants market and brand themselves. Even though they have excellent reach and visibility, billboards and other OOH mediums cannot track the exact number of impressions, duration, and whether those viewers actually visited a restaurant’s physical location. This is where <a href="http://abraxastechnology.com/">Abraxas Technology</a> comes in. With our proprietary technology and Scout device, we can provide that missing data for OOH owners and advertisers.</p>
                <p>For Estância Brazilian Steakhouse, our technology would allow them to perform A/B testing on which billboard locations drive the most traffic to their restaurants. For example, I saw their billboard on US-183 and made the decision to come dine in. Wouldn’t it be great for Estância’s managers to know what other customers saw that specific sign and how many came in compared to advertising venues they may have placed elsewhere?</p>
                <p>Non-traditional food businesses such as food trucks also have much to gain from data analytics. Given their mobility, food trucks are in a unique position to spread their reach and visibility. They are not tied down to a brick &amp; mortar location. But nevertheless, their owners would greatly benefit knowing how much visibility and conversions they receive at a particular location compared to others. With Abraxas’s data, that knowledge is attainable. Afterwards, these food trucks will know what locations to return to more often.</p>
                <p>For Salt Lick and traditional Texan BBQ joints, a directional billboard definitely helps guide customers to their physical addresses. Then using the analytics provided by Abraxas, the owners can then accurately measure the traffic that resulted in storefront conversions.</p>
                <p>At the end of the day, one of the most hyperlocal business industries are restaurants. Their products and services are physical, and the vast majority of their customers come from nearby areas. These characteristics make advertising on billboards one of the most effective mediums for restaurateurs to reach out and entice customers to come to their locations.</p>
                <p>As a BBQ lover, Texan, and entrepreneur, I wish Salt Lick and other BBQ joints every bit of success in their marketing campaigns. Let us make them even more effective by equipping billboard owners and advertisers with the data analytics and metrics to ensure the best ROI.</p>
                <p>May the message of meat be magnified and be spread far and wide.</p>
                <p>______________________________________________________________________________</p>
                <p><a href="https://www.linkedin.com/in/aarontao/"><strong>Aaron Tao</strong></a> is a Product Manager with Abraxas Technology.</p>
                <p>Reach out to us today if you want to learn how out of home advertising can help you increase traffic to your restaurant or food truck. Email <a href="mailto:JLawton@abraxastechnology.com">JLawton@abraxastechnology.com</a>.</p>
                <p><i>Follow us on Twitter </i><a href="https://twitter.com/Abraxas_Tech"><i>@</i><b><i>Abraxas_Tech</i></b></a></p>


            </div>

        </div>

    </article>
);

export default PostPreview11;
